---
title: "GIS-Deliverable"
author: "Catharina Clark"
date: "2025-03-04"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries

```{r libraries}

library(httr)
library(sf) 
library(ggplot2)
library(ggspatial)
library(leaflet)
library(dplyr)
library(rinat)

```


## Striped Mouse Data Retrievals from iNat

```{r data}

data_striped_mouse <- get_inat_obs(
  taxon_name = "Rhabdomys pumilio",
  quality = "research", 
  geo = TRUE, 
  place_id = 113055, 
  maxresults = 1000     
)

head(data_striped_mouse)
names(data_striped_mouse)


```


## Vlei Rat Data Retrievals from iNat

```{r data}

data_vlei_rat <- get_inat_obs(
  taxon_name = "Elephantulus edwardii",
  quality = "research", 
  geo = TRUE, 
  place_id = 113055, 
  maxresults = 1000     
)

head(data_vlei_rat)
names(data_vlei_rat)


```


## Making into Map

```{r}

striped_mouse_map <- leaflet(data = data_striped_mouse) %>%
  addTiles() %>%  
  addCircleMarkers(lng = ~longitude, lat = ~latitude, 
                   popup = ~paste("ID:", id, "<br>Species:", scientific_name, 
                                  "<br>Observation Date:", observed_on),
                   color = "green", radius = 5, stroke = FALSE, fillOpacity = 0.7)

striped_mouse_map

vlei_rat_map <- leaflet(data = data_vlei_rat) %>%
  addTiles() %>%  
  addCircleMarkers(lng = ~longitude, lat = ~latitude, 
                   popup = ~paste("ID:", id, "<br>Species:", scientific_name, 
                                  "<br>Observation Date:", observed_on),
                   color = "blue", radius = 5, stroke = FALSE, fillOpacity = 0.7)

vlei_rat_map
```

